__author__='callMeBin'
#-*-coding:utf-8-*-

'''
目标：实现图片转字符串画
'''

from PIL import Image
import argparse

class img2Char():
	def __init__(self):
		self.IMG = r'C:/Users/LENOVO/Desktop/img1/569.jpg'
		self.WIDTH =100
		self.HEIGHT =50

		#@#&$*ox!i;.
		#$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]?-_+~<>i!;:,\"^`.
		self.ascii_char = list(r"@MNGQ&OCo0>!:-;.")


	def get_char(self,r,g,b,alpha=256):
		if alpha==0:
			return ' '
		length = len(self.ascii_char)
		#gray = (0.299*r+0.587*g+0.114*b)
		#gray = (299*r+587*g+114*b+500)/1000
		gray = (r**2.2*0.2973+g**2.2*0.6274+b**2.2*0.0753)**(1/2.2)
		unit = (256.0+1)/length
		return self.ascii_char[int(gray/unit)]


	def save2File(self):
		im = Image.open(self.IMG)
		scale = max(im.size[0]/self.WIDTH,im.size[1]/self.HEIGHT)
		self.WIDTH =int(im.size[0]/scale *2)
		self.HEIGHT = int(im.size[1]/scale)
		im = im.resize((self.WIDTH,self.HEIGHT),Image.ANTIALIAS)
		txt = ""

		for i in range(self.HEIGHT):
			for j in range(self.WIDTH):
				txt +=self.get_char(*im.getpixel((j,i))[:3])
			txt+='\n'

		with open(r'C:/Users/LENOVO/Desktop/img1/output.txt','w') as f:
			f.write(txt)


img2char = img2Char()
img2char.save2File()

'''

....................................................................................................
....................................................................................................
....................................................................................................
...........................`...^`...............................""JYJJJJYZ^`........................
.................```^JUUUUUUUUUUUUUUUUUU`^``............`,\UUUUUUUUUUUUUUUUUUUUY`^^.................
................`cLUUUUUUUUUUUUUUUUUUUUUUUUY,``......`.vCUUUUUUUUUUUUUUUUUUUUUUUUUQ``...............
.............`iUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUJ`...."UUUUUUUUUUUUUUUUUJ\`````\XUUUUUU,`.............
............,UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUm`^UUUUUUUUUUUUUUUUUUUUUUUUC```..ZJUUUU^............
...........jUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU~vUUUUUUUUUUUUUUUUUUUUUUUUUUU0i`..UUUUUO...........
..........zUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUX<.,UUUUX..........
........`UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU`)JUUU/^........
........cUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUXQUUUU`........
.......`UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU........
.......UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU`.......
.......UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUu.......
......`UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.....`\UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.....`vUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.....`|UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.......UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.......UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.......UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.......
.......,UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUX.......
.......`XUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU`.......
........"UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU........
.........CUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU`........
.........`QUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU^.........
...........JUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU``.........
............XUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU:...........
............`ZUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU.............
.............`\UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUC^`............
...............^YUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUa...............
................`uUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU`................
...................cUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUr`.................
...................."UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUY^...................
.....................`^UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU``....................
........................{UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUJUC`.......................
.........................`;UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUX`.........................
...........................`^UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUO`...........................
...............................UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUQ`..............................
................................`QUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUJ^................................
...................................^UUUUUUUUUUUUUUUUUUUUUUUUUUUz```.................................
......................................^LUUUUUUUUUUUUUUUUUUUUX.......................................
........................................`^UUUUUUUUUUUUUUUJ,`........................................
...........................................`iUUUUUUUUUU`............................................
...............................................^JUUX^...............................................
..................................................`.................................................
....................................................................................................
+++++_+++~++?+++++++++++............................................................................
+___+__+++_+__?+++++++++............................................................................








'''